use_frameworks!

platform :ios, '13.0'

target 'CombineCocoaKit_Example' do
  pod 'SnapKit'
  pod 'CombineCocoaKit', :path => '../'

  target 'CombineCocoaKit_Tests' do
    inherit! :search_paths

    
  end
end
